import DataLineMyProject1ТипОборудованияEController from '../data-line-my-project1-тип-оборудования-e';

var DataLineMyProject1ТипОборудованияENewController = DataLineMyProject1ТипОборудованияEController;
export default DataLineMyProject1ТипОборудованияENewController;
